# **Python**

The following questions are designed to test your basic understanding of python in topics such as recursion, functions, loop and classes. DO NOT use ChatGPT for this as it is important that you understand and clarify the basics here because it won't be able to help you on later stages of this project. So it's best to discuss your doubts on the group or ask us mentors. Have fun solving this assignment :)

**Q1. Create a function to calculate a factorial of a number, using recursion.**

In [4]:
def nFactorial(n: int = 0) -> int:
    if n == 0 or n == 1:
        return 1
    else:
        return n * nFactorial(n - 1)


**Q2. Create a class called "Car" that inherits from a parent class called "Vehicle". Additionally, the "Car" class should have a method to calculate the fuel efficiency, a property to track the current speed, and a class variable to keep track of the total number of cars created.**

In [5]:
class Vehicle:
    pass


class Car(Vehicle):
    TotalCars = 0
    
    def __init__(self):
        Car.TotalCars += 1
        self.current_speed = 0
        
    def fuel_efficiency(self):
        pass

**Q3. Write a function called "reverse_string" that takes a string as input and returns the reverse of the input string.**

In [6]:
def reverse_string(input_string: str) -> str:
    reversed_string = ""
    for letter in input_string:
        reversed_string = letter + reversed_string
    return reversed_string

**Q4. Write a program to calculate the sum of all the even numbers between 1 and 100 which are not divisible by 5 and 7 using a for-loop**

In [10]:
req_sum = 0
for i in range(2, 100, 2):
    if (i % 7 != 0) and (i % 5 != 0):
        req_sum += i
    
print(req_sum)

1678


**Q5. Create a dictionary with the following key-value pairs: "name" - "John", "age" - 25, "city" - "New York". Write a program that prints out the keys and values of the dictionary.**

In [3]:
my_dict = {"name": "John", "age": 25, "city": "New York"}

for key, value in my_dict.items():
    print(f"key: {key}, value: {value}")


key: name, value: John
key: age, value: 25
key: city, value: New York


**Q6. Write a function that takes a list of numbers as input and returns the second-largest number in the list, without using any built-in sorting functions or the max() function.**

In [1]:
# Assuming a minimum of 2 values in the list (of floats). Also, the second-largest number in [23, 23, 17, 6, 9] is 17.
def second_largest(numbers) -> float:
    largest = second = float('-inf')
    for number in numbers:
        if number > largest:
            second = largest
            largest = number
        elif second < number < largest:
            second = number
    if second == float('-inf'):
        raise ValueError("List must contain at least two distinct numbers")
    return second

second_largest([23, 23, 17, 6, 9])

17

# **NumPy**
In this assignment, you will be familiarized with the usage of the NumPy library and how to use vectorization to speed up computations in comparison to iterative approaches.

You are to only write/modify the code in between consecutive `# < START >` and `# < END >` comments. DO NOT modify other parts of the notebook, your assignments will not be graded otherwise.
```python
"Don't modify any code here"

# < START >
"YOUR CODE GOES HERE!"
# < END >

"Don't modify any code here"
```

<!---Need to include clarification about arrays?-->

**Start by running the below cell, to import the NumPy library.**

In [3]:
import numpy as np

### **Initializing Arrays**
NumPy offers multiple methods to create and populate arrays
- Create a $2\times3$ array identical to
$\begin{bmatrix}
1 & 2 & 4\\
7 & 13 & 21\\
\end{bmatrix}$, and assign it to a variable `arr`.  

In [8]:
# < START >
arr = np.array([[1, 2, 4], [7, 13, 21]])
# < END >

print(arr)
print("Shape:", arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape: (2, 3)


You should be able to see that the `shape` property of an array lets you access its dimensions.  
For us, this is a handy way to ensure that the dimensions of an array are what we expect, allowing us to easily debug programs.

- Initialize a NumPy array `x` of dimensions $2\times3$ with random values belonging to $[0, 1)$.  
Do not use the values of the dimensions directly, instead use the variables provided as arguments.

In [7]:
n_rows = 2
n_columns = 3

# <START>
x = np.random.random((n_rows, n_columns))
# <END>

print(x)

[[0.80162909 0.99549866 0.05512352]
 [0.71557576 0.82245418 0.93620393]]


A few more basic methods to initialize arrays exist.
Feel free to read up online to complete the code snippets.

In [8]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) who's every element is 0
ZERO_ARR = np.zeros((4, 5, 2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) who's every element is 1
ONE_ARR = np.ones((4, 5, 2))
# < END >

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


You can also transpose arrays (same as with matrices), but a more general and commonly used function is the `array.reshape()` function.

$$
\begin{bmatrix}
a & d\\
b & e\\
c & f\\
\end{bmatrix}
\xleftarrow{\text{.T}}
\begin{bmatrix}
a & b & c\\
d & e & f\\
\end{bmatrix}
\xrightarrow{\text{.reshape(3, 2)}}
\begin{bmatrix}
a & b\\
c & d\\
e & f\\
\end{bmatrix}
\xrightarrow{\text{.reshape(6,1)}}
\begin{bmatrix}
a\\
b\\
c\\
d\\
e\\
f\\
\end{bmatrix}
$$


`reshape` is commonly used to flatten data stored in multidimensional arrays (ex: a 2D array representing a B/W image)

- Try it out yourself:

In [11]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose = y.T
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat = y.reshape(-1, 1)
# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- Create a `y` with dimensions $3\times1$ (column matrix), with elements $4,7$ and $11$.  
$$y = \begin{bmatrix}
4\\
7\\
11
\end{bmatrix}$$  

In [12]:
# <START>
# Initialize the column matrix here
y = np.array([4, 7, 11]).reshape(-1, 1)
# <END>

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

# <START>
# Multiply both the arrays here
xMul = np.ones((2, 3))
z = np.matmul(xMul, y)
# <END>

assert z.shape == (2, 1)

print(z)

[[ 4]
 [ 7]
 [11]]
[[22.]
 [22.]]


### **Indexing & Slicing**
Just like with normal arrays, you can access an element at the `(i,j)` position using `array[i][j]`.  
However, NumPy allows you to do the same using `array[i, j]`, and this form is more efficient and simpler to use.
<details>
<summary><i>(Optional) Why is it more efficient?</i></summary>
The former case is more inefficient as a new temporary array is created after the first index i, that is then indexed by j.
</details>

```python
x = np.array([[1,3,5],[4,7,11],[5,10,20]])

x[1][2] #11
x[1,2]  #11 <-- Prefer this
```

Slicing is another important feature of NumPy arrays. The syntax is the same as that of slicing in Python lists.
  We pass the slice as

```python
  sliced_array = array[start:end:step]
  # The second colon (:) is only needed
  # if you want to use a step other than 1
```
By default, `start` is 0, `end` is the array length (in that dimension), and `step` is 1.
Remember that `end` is not included in the slice.

  Implement array slicing as instructed in the following examples



In [13]:
x = np.array([4, 1, 5, 6, 11])

# <START>
# Create a new array y with the middle 3 elements of x
y = x[1:-1]
# <END>

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# <START>
# Create a new array w with alternating elements of z
w = z[::2]
# <END>

print(w)

[1 5 6]
[1 3 5 7 9]


A combination of indexing and slicing can be used to access rows, columns and sub-arrays of 2D arrays.

```python
arr = np.array([
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

print(arr[0])       #[1 2 3]
print(arr[:,2])     #[3 6 9]
print(arr[0:2,0:2]) #[[1 2]
                    # [4 5]]
```

In [4]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

# <START>
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d = arr_2d[:3, 1:]
# <END>

print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


### **Broadcasting**

This feature allows for flexibility in array operations. It lets us implement highly efficient algorithms with minimal use of memory.

In [5]:
arr1 = np.array([1, 2, 3, 4])
b = 1

# <START>
# Implement broadcasting to add b to each element of arr1
arr1 += b
# <END>

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

# <START>
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2 *= arr3
# <END>

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


### **Vectorization**

From what we've covered so far, it might not be clear as to why we need to use vectorization. To understand this, let's compare the execution times of a non-vectorized program and a vectorized one.

Your goal is to multiply each element of the 2D arrays by 3. Implement this using both non-vectorized and vectorized approaches.

In [11]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
# <START>
for i in range(1000):
    for j in range(1000):
         arr_nonvectorized[i][j] *= 3
# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
# <START>
arr_vectorized *= 3
# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_vectorized)

print(np.array(arr_nonvectorized) == arr_vectorized)

Time taken in non-vectorized approach: 240.7369613647461 ms
Time taken in vectorized approach: 0.8740425109863281 ms
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


Try playing around with the dimensions of the array. You'll find that there isn't much difference in the execution times when the dimensions are small. But in neural networks, we often deal with very large datasets and so vectorization is a very important tool.

# **Pandas**

This section will help you get familiar with various functions of pandas and how to use them.

As you go through this section, you will find a ??? in certain places. To complete this section, you must replace all the ??? with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end


Let's start by importing the pandas library

In [ ]:
import pandas as pd

### **Loading data using url**

In [ ]:
url = "https://raw.githubusercontent.com/Mehul-Agrawal410/SpeakSpeare/main/Week%201/countries.csv"

df = ???
df

*(Optional)*: You can rename the columns for your convenience later on. Look up the syntax for renaming columns

**Q1: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [ ]:
num_countries = ???
print(f'There are {num_countries} countries in the dataset')

**Q2: Retrieve a list of the Regions from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [ ]:
continents = ???
continents

**Q3: What is the total population of all the countries listed in this dataset?**

In [ ]:
total_population = ???
print(f'The total population is {total_population}.')

**Q4: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [ ]:
most_populous_df = ???
most_populous_df

**Q5: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [ ]:
df['gdp'] = ???
df

**Q6: Create a data frame that counts the number countries in each region?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [ ]:
country_counts_df = ???
country_counts_df

**Q7: Create a data frame showing the total population of each region.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [ ]:
region_populations_df = ???
region_populations_df

**Q8: Count the number of null values in each column**

*Hint: Use `isna`.*

In [ ]:
na_values = ???
na_values

**Q9: Fill all the null values with the mean of their respective column**

*Hint: Use `mean` and `fillna`.*

In [ ]:
# <START>

# <END>

**Q10: Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [ ]:
# <START>

# <END>

# **Matplotlib**


Data visualisation is a very important part of data science. It helps us understand the data better and draw conclusions from it and Matplotlib is the most popular library in python for this step.

In this section, you'll navigate through a series of challenges that not only familiarize you with Matplotlib but also showcase the diverse array of plots and their practical applications. This will not only enhance your Matplotlib skills but also sharpen your ability to choose the right plot for the right scenario.

So let's delve in and master the craft of transforming data into compelling visual insights. We will have start with importing the matplotlib library

In [ ]:
import matplotlib.pyplot as plt

Now, let's start with a simple x vs y plot.
1. Create 2 numpy arrays `x` and `y` of random integers, of size (5,1)
2. Create a plot of `x` vs `y` using the `plot()` function
3. Add labels to the X and Y axes
4. Add a title to the plot

In [ ]:
# <START>

# <END>
plt.show()

### **Bar Graphs**

Bar graph uses bars to compare data among different categories. It is well suited when you want to measure the changes over a period of time. It can be represented horizontally or vertically. Also, the important thing to keep in mind is that longer the bar, greater is the value.

We will be plotting a grouped bar chart in this task. More often than not, it’s more interesting to compare values across two dimensions and for that, a grouped bar chart is needed. (Although no need to worry, making a grouped chart is just calling the `.bar()` command twice :)

In [ ]:
# Create the data to be plotted
x1 = np.array([0.25,1.25,2.25,3.25,4.25]) #this will decide the x-coordinate of the centre of the bars
y1 = np.array([10,55,80,32,40])
width = 0.5 # width of the bars
x2 = x1 + width # this will shift the x-coordinate of the centre of the bars by width
y2 = np.array([42,26,10,29,66])

Now,
1. Create the bar graphs. Assign different label and color to both the plots.
2. Create legend, title and axes labels
3. Play around with the values to get a sense of how everything is working

### **Histograms**

Histograms are used to show a distribution whereas a bar chart is used to compare different entities. Histograms are useful when you have arrays or a very long list. I have to plot the age of population with respect to bin. Now, bin refers to the range of values that are divided into series of intervals. Bins are usually created of the same size.

For this task, you should:
1. Create bins of interval 10 from 0 to 100. Use `np.arange`
2. Generate data to be plotted. You can use numpy for this or write the data yourself. Pick atleast 30 values.
3. Plot the histogram, label the axes and title the plot
4. Customise the color and width of the plot as per your choice

### **Scatter plot**

Usually we need scatter plots in order to compare variables, for example, how much one variable is affected by another variable to build a relation out of it. The data is displayed as a collection of points, each having the value of one variable which determines the position on the horizontal axis and the value of other variable determines the position on the vertical axis

1. Create 2 sets of data, `(x1,y1)` and `(x2,y2)` with 8 values each
2. Create the scatter plots for both of them and give different labels to each
3. Stylise each plot, by giving different colors and marker style. *(Use `marker` argument)*
4. Provide legend

### **Subplots**

*Look up the `subplot()` command and it's use*

1. Generate multiple datasets for different plots.
2. Create a figure with multiple subplots (e.g., a 2x2 grid).
3. Plot different types of charts (line, scatter, bar) in each subplot. You are free to choose any kind of data and plot.